# Generated by Django 6.0.3 on 2026-03-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='fields_processed',
            field=models.TextField(blank=True),
        ),
    ]
